services:
  mjg-firearms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - mjg-network

networks:
  mjg-network:
    driver: bridge
